### ISSUE TITLE
[Anon] Bug report: Necromunda-Gang-War.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/necromunda-gang-war#48] opened 2019-01-29 12:09 UTC
**File:** Necromunda-Gang-War.gstz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Really need Delaque adding to The Gang Lists. I would do it myself but I’m not sure how...

**Comment by tw6464** [comment] 2019-01-29 16:37
You and me both, friend. It'd be wonderful if people would help but unfortunately, more important games that absolutely everyone plays like Harry Potter Miniatures game, the 9th Age, the Song of Ice and Fire game, Gates of Antares, Kings of War, Kings of War: Vanguard, Maelstrom's Edge, Warhammer Historical, Warzone: Resurrection, AvP: Unleashed, Dropfleet Commander, Monsterpocalypse, Kill Zone by Nick Lund, The Walking Dead: All Out War and Trinity: Battleground.

You know. All THOSE games, clearly more important than Necromunda, even though every other repository for every GW game that's currently being supported has been updated in a relatively recent time from.

**Comment by OftKilted** [comment] 2019-01-30 02:13
Closing as this is a duplicate of #46

**Closed as completed by OftKilted** 2019-01-30 02:13 UTC
Labels: enhancement, help wanted, good first issue, question
