### ISSUE TITLE
[Anon] Bug report: Necromunda-Gang-War.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/necromunda-gang-war#44] opened 2018-12-28 08:24 UTC
**File:** Necromunda-Gang-War.gstz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Would be really great if you guys add house Delaque..maybe after the holidays.. 
Have a happy new year.

**Comment by OftKilted** [comment] 2019-01-30 02:14
Closing, duplicate of #46

**Closed as completed by OftKilted** 2019-01-30 02:14 UTC
Labels: enhancement, help wanted, good first issue, question
