### ISSUE TITLE
[Anon] Bug report: Escher.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/necromunda-gang-war#3] opened 2018-03-26 16:19 UTC
**File:** Escher.catz

**BattleScribe version:** 2.01.09

**Platform:** Mac

**Dropbox:** No

**Description:** House Escher Juve, Autopistol listed at 1 point instead of 10

**Comment by cjo197** [comment] 2018-05-05 15:12
Duplicate of #1

**Closed as completed by cjo197** 2018-05-05 15:12 UTC
Labels: duplicate
