### ISSUE TITLE
Bug: File Problems when both Underhive and Gang War game files are downloaded

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/necromunda-gang-war#27] opened 2018-07-29 15:40 UTC
**File:** Goliath.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** In the V 1.4.0 of Gang War, there are options missing from the rosters of Escher and Goliath, the ones I saw are no Juves and only the basic equipment from the Rulebook. Did I do something wrong? I downloaded the Underhive 1.0.0 and gang war 1.4.0, do I need to download any more data files?

The Gang war file was downloaded by the data manager of the app.

**Comment by OftKilted** [comment] 2018-08-23 02:09
Issue caused by duplicate files, and identical GST ID's between Gang Wars and Underhive games Closing issue.

**Closed as completed by OftKilted** 2018-08-23 02:09 UTC
Labels: duplicate
